version: 2
project_name: terraform-provider-cachefly
builds:
  - id: terraform-provider-cachefly
    binary: "{{ .ProjectName }}_v{{ .Version }}"
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    env:
      - CGO_ENABLED=0

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

release:
  github:
    owner: alehyarmalovich
    name: terraform-provider-cachefly
  draft: true

changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
